package mps.samples.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptPropertyOperations;

public class BuildInType_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String virtual_getTypeName_6444818056879371775(SNode thisNode) {
    return SConceptPropertyOperations.getString(thisNode, "alias");
  }

}
