package mps.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.BaseConcept_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class JavaType_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String virtual_getTypeName_6444818056879371775(SNode thisNode) {
    return BaseConcept_Behavior.call_getPresentation_1213877396640(SLinkOperations.getTarget(thisNode, "javaType", true));
  }

}
