package mps.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class PropertyType_Behavior {
  private static Class[] PARAMETERS_6444818056879371775 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static String virtual_getTypeName_6444818056879371775(SNode thisNode) {
    return "TODO";
  }

  public static String call_getTypeName_6444818056879371775(SNode thisNode) {
    return (String)BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(thisNode, "mps.typesystem.structure.PropertyType"), "virtual_getTypeName_6444818056879371775", PARAMETERS_6444818056879371775);
  }

  public static String callSuper_getTypeName_6444818056879371775(SNode thisNode, String callerConceptFqName) {
    return (String)BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "mps.typesystem.structure.PropertyType"), callerConceptFqName, "virtual_getTypeName_6444818056879371775", PARAMETERS_6444818056879371775);
  }

}
