package mps.samples.typesystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class JavaType extends PropertyType {
  public static final String concept = "mps.samples.typesystem.structure.JavaType";
  public static final String JAVA_TYPE = "javaType";

  public JavaType(SNode node) {
    super(node);
  }

  public Type getJavaType() {
    return (Type)this.getChild(Type.class, JavaType.JAVA_TYPE);
  }

  public void setJavaType(Type node) {
    super.setChild(JavaType.JAVA_TYPE, node);
  }


  public static JavaType newInstance(SModel sm, boolean init) {
    return (JavaType)SModelUtil_new.instantiateConceptDeclaration("mps.samples.typesystem.structure.JavaType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static JavaType newInstance(SModel sm) {
    return JavaType.newInstance(sm, false);
  }

}
