package mps.typesystem.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Typesystem_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("d65db576-7c4e-467b-b8ec-c84f7dda90ee(mps.typesystem)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }

}
