package de.nerche.mps.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class PropertyType_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String call_getTypename_6444818056879371775(SNode thisNode) {
    return "TODO";
  }

}
