package mps.samples.typesystem.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import mps.samples.typesystem.behavior.PropertyType_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

public class QueriesGenerated {

  public static Object propertyMacro_GetPropertyValue_6062868430809606160(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "define entity " + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6062868430809897925(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return PropertyType_Behavior.call_getTypeName_6444818056879371775(SLinkOperations.getTarget(_context.getNode(), "propertyType", true));
  }

  public static Object propertyMacro_GetPropertyValue_6062868430809897939(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Iterable sourceNodesQuery_1207237555457694571(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "item", true);
  }

  public static Iterable sourceNodesQuery_6062868430809897911(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "property", true);
  }

}
