package de.nerche.mps.typesystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EnumTypeReference extends PropertyType {
  public static final String concept = "de.nerche.mps.typesystem.structure.EnumTypeReference";
  public static final String ENUM_TYPE = "enumType";

  public EnumTypeReference(SNode node) {
    super(node);
  }

  public EnumType getEnumType() {
    return (EnumType)this.getReferent(EnumType.class, EnumTypeReference.ENUM_TYPE);
  }

  public void setEnumType(EnumType node) {
    super.setReferent(EnumTypeReference.ENUM_TYPE, node);
  }


  public static EnumTypeReference newInstance(SModel sm, boolean init) {
    return (EnumTypeReference)SModelUtil_new.instantiateConceptDeclaration("de.nerche.mps.typesystem.structure.EnumTypeReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EnumTypeReference newInstance(SModel sm) {
    return EnumTypeReference.newInstance(sm, false);
  }

}
