package de.nerche.mps.typesystem.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Enum {
  one("one", "one"),
  two("two", "two"),
  three("three", "three");

  private String myName;
  private String myValue;

  Enum(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }


  public static List<Enum> getConstants() {
    List<Enum> list = ListSequence.fromList(new LinkedList<Enum>());
    ListSequence.fromList(list).addElement(Enum.one);
    ListSequence.fromList(list).addElement(Enum.two);
    ListSequence.fromList(list).addElement(Enum.three);
    return list;
  }

  public static Enum getDefault() {
    return Enum.one;
  }

  public static Enum parseValue(String value) {
    if (value == null) {
      return Enum.getDefault();
    }
    if (value.equals(Enum.one.getValueAsString())) {
      return Enum.one;
    }
    if (value.equals(Enum.two.getValueAsString())) {
      return Enum.two;
    }
    if (value.equals(Enum.three.getValueAsString())) {
      return Enum.three;
    }
    return Enum.getDefault();
  }

}
